### ISSUE TITLE
Extended Cogwheel and Encased creates a null? [Bug?] 

### ISSUE THREAD

**Issue by DragonGirl7567** [iglee42/CreateCasing#10]
Describe the bug
Error appears with latest updates

To Reproduce

Launch Minecraft
Error apears

Screenshots
![Minecarft Null](https://user-images.githubusercontent.com/99091439/230777028-86ae60f7-872e-4f30-b209-85627ffea6d9.PNG)

OS: Windows
Minecraft Version 1.19.2
Forge Version 43.2.7
Create: Extended Cogwheels | Rabbitminers | extendedgears-2.0.2-1.19.2-0.5.0.iforge-1.19.2.jar
Create Encased | iglee42 | CreateCasing-1.19.2-1.1.1-hotfix-2.jar
Flywheel | jozufozu | flywheel-forge-1.19.2-0.6.8.a.jar
Create | simibubi | create-1.19.2-0.5.0.i.jar

Additional context
Sorry to keep bothering

**Comment by iglee42** [comment]
Fixed
