### ISSUE TITLE
[Feature] Fabric port please

### ISSUE THREAD

**Issue by Yoshiman5551** [iglee42/CreateCasing#100]
Please port this mod to Fabric. I love it, but it's a shame it's only on 🅱️orge.
(I deleted the template because none of it really matched what I wanted to say)

**Comment by iglee42** [comment]
I don't know how to makes fabric mod and I don't have the time to learn

**Comment by Yoshiman5551** [comment]
> I don't know how to makes fabric mod and I don't have the time to learn

Do I have permission to make a port?

**Comment by iglee42** [comment]
> > I don't know how to makes fabric mod and I don't have the time to learn
> 
> Do I have permission to make a port?

Yes for sure
