### ISSUE TITLE
just a visual [Bug] with encased cogwheels

### ISSUE THREAD

**Issue by poly-1810** [iglee42/CreateCasing#16]
**The Bug:**
basically, if you encase a shaft in copper casings, it has the regular encased texture for copper casings, but if you encase a large cogwheel in copper casings and make a face with a shaft in it, the shaft side will use andesite casing texture instead of copper casing texture. same goes for train casings and large cogwheels

**To Reproduce**
1. Launch Minecraft
2. Join a World
3. Place down a large cogwheel and encase with copper or train casing
4. Wrench the face to have a shaft show

**Expected behavior**
using the regular texture?

**Screenshots**
![image](https://github.com/iglee42/CreateCasing/assets/105131270/6ab7c24f-ceb2-4771-affb-5eb191b0d6d7)

**Desktop (please complete the following information):**
 - OS: windows
 - Minecraft Version: 1.18.2
 - Forge Version: 40.2.4
 - Create Version: 0.5.1b
 - Flywheel Version: not applicable 
 - Mod Version: 1.2.1
 - Other Mods: tested with no other mods, issue still occurs

**Comment by iglee42** [comment]
It will be fixed in the next update
