### ISSUE TITLE
[Bug]Issue on copper glass casing from Create:Crystal clear

### ISSUE THREAD

**Issue by ghost** [iglee42/CreateCasing#18]
**Describe the bug**
Some unnecessary block faces are not culled

**Screenshots** 
![2023-06-21_15 38 06](https://github.com/iglee42/CreateCasing/assets/129179911/03220d15-ad7a-4979-bb49-e8709e34fa7c)

**Desktop (please complete the following information):**
Mods:
Create-1.19.2-0.5.1.b
CreateCasing-1.19.2-1.2.1
Create_crystal_clear-0.2.1-1.19.2

**Comment by iglee42** [comment]
That will be fix in the next update
