### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by poly-1810** [iglee42/CreateCasing#19]
**Describe the bug**
welp, it appears the train encased mixer creates a phantom mix head that kinda follows you whenever you unrender it from the chunk

**To Reproduce**
1. Launch Minecraft
2. Join a World
3. Set up a Train encased mixer
4. phantom mixer head

**Expected behavior**
no phantom mixer head?

**Screenshots**
![image](https://github.com/iglee42/CreateCasing/assets/105131270/4ac3d33b-0172-43fb-8b34-4f69958c0d15)
![image](https://github.com/iglee42/CreateCasing/assets/105131270/3970b608-902c-456e-ae3d-266e592d8a43)

**Desktop (please complete the following information):**
 - OS: windows
 - Minecraft Version 1.18.2
 - Forge Version 40.2.9
 - Create Version 0.5.1b
 - Flywheel Version n/a
 - Mod Version most recent(?)
 - the modlist from https://www.curseforge.com/minecraft/modpacks/create-charged-up dev builds

**Additional context**
havent tested it with other encased mixers, but i will eventually. also, another small thing, maybe make it a config option for the encased mixers to mix faster, rather than it always being enabled?

**Comment by iglee42** [comment]
This bug will be fixed in the next update and config will be added

**Comment by iglee42** [comment]
FIXED
