### ISSUE TITLE
[Bug]Brass & Train Mixer not mixing correclty 

### ISSUE THREAD

**Issue by f0kx** [iglee42/CreateCasing#20]
**Describe the bug**
When i want to Mix steel inside a basin i can mix it with normal mixer and copper mixer but train and brass mixer arnt working correclty.

**To Reproduce**
1. Launch Minecraft
2. Join a World
3. Mix something

**Expected behavior**
Brass & Train Mixer should Mix

**Screenshots**
I
![image](https://github.com/iglee42/CreateCasing/assets/14795020/1eca4d3d-b2a2-4d87-bc12-32b5718eb053)

**Desktop (please complete the following information):**
 - Windows 11
 - Minecraft Version 1.19.2
 - Forge Version 43.2.11
 - Create Version 0.5.1b
 - Flywheel Version 0.6.8.a
 - Mod Version 1.3
 - Many :P [nearly all Create Addons]

**Comment by iglee42** [comment]
I can't reproduce the bug

**Comment by iglee42** [comment]
Bug can't be reproduce
