### ISSUE TITLE
[Bug] It makes picaxe and axe breakable blocks break at hand speed

### ISSUE THREAD

**Issue by carloscopy** [iglee42/CreateCasing#23]
**Describe the bug**

**To Reproduce**
1. Launch Minecraft
2. Join a World
3. Right Click on '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Minecraft Version 1.19.2
 - Forge Version 43.2.21
 - Create Version 0.5.1c
 - Flywheel not necessary
 - Mod Version [e.g. 1.0]
 - Other Mods Lots of them

**Additional context**

**Comment by satoon10** [comment]
Why is it marked as not planned?

**Comment by iglee42** [comment]
I need for informations to fix this bug
