### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by CapToad** [iglee42/CreateCasing#26]
**Describe the bug**
tools become useless with the 1.19.2 1.4 update

**To Reproduce**
download the mod use any (i think) tool and for example break stone

**Expected behavior**
you are able to break blocks

**Screenshots**
cant really show it via screenshots

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft Version 1.19.2
 - Forge Version 43.2.21
 - Create Version 0.5.1.c
 - Flywheel Version none (create mod already has it)
 - Mod Version 1.4
 - Other Mods (i tested it and figured out it was because of create encased)

**Additional context**
none

**Comment by iglee42** [comment]
This bug will be fixed
