### ISSUE TITLE
[Bug] Pickaxe still not fuctioning properly 

### ISSUE THREAD

**Issue by LadyValishade** [iglee42/CreateCasing#28]
**Describe the bug**
Pickaxe mines very slow and does not drop item.

**To Reproduce**
1. Launch Minecraft
2. Join a World
3. Mine Stone with Pickaxe
4. Mines very slow and does not drop stone

**Expected behavior**
Stone to drop and pickaxe to function properly

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft Version 1.19.2
 - Forge Version 43.2.10
 - Mod Version CreateCasing-1.19.2-1.4.1.jar
 - Other Mods: create-1.19.2-0.5.1.c.jar

**Additional context**
I originally had this part of a large modpack. but was able to narrow it down to something create related.
I then created a new profile with only this mod and create on it and pickaxes are still broken.

**Comment by iglee42** [comment]
Can I have a video please because I know this bug exist , I fixed it and I can't reproduce it

**Comment by CapToad** [comment]
https://imgur.com/a/pgrpL1c
didnt want to post it on youtube so here it is on imgur
edit: yes it is vanilla stone

**Comment by iglee42** [comment]
Bug Fixed
