### ISSUE TITLE
[Bug] wrong casing texture on large encased cogwheel

### ISSUE THREAD

**Issue by poly-1810** [iglee42/CreateCasing#31]
**Describe the bug**
simply wrong texture

**To Reproduce**
1. Launch Minecraft
2. Join a World
3. encase a large cogwheel with industrial iron
4. wrench face to show shaft

**Expected behavior**
same as reg small cogwheel perhape?

**Screenshots**
![image](https://github.com/iglee42/CreateCasing/assets/105131270/c6eaee03-137f-48cc-add7-6020f259fcbd)

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft Version: 1.18.2
 - Forge Version: most recent for forge 1.18.2
 - Mod Version: most recent 1.18 vers on curseforge
 - https://www.curseforge.com/minecraft/modpacks/create-charged-up, an indev build of it

**Additional context**
pretty basic texture issue, prolly easily fixed

**Comment by iglee42** [comment]
Fixed
