### ISSUE TITLE
[Bug] Axes break wood at hand speed

### ISSUE THREAD

**Issue by OliverWolf621** [iglee42/CreateCasing#33]
**Describe the bug**
Axes do not break wood faster

**To Reproduce**
1. Launch Minecraft
2. Join a World
3. Try to break any wood with any axe
4. Wood does not break any faster than by hand

**Expected behavior**
Wood should break as fast as vanilla

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Minecraft Version: 1.18.2
 - Forge Version: 40.2.10
 - Mod Version: 1.4.1-hotfix-1
 - Other Mods: Create

**Additional context**

**Comment by iglee42** [comment]
As I said on discord , I see why the bug persist , and It will fix
