### ISSUE TITLE
Custom Shafts Place Shaftless Cogwheels

### ISSUE THREAD

**Issue by Dejojotheawsome** [iglee42/CreateCasing#39]
**Describe the bug**
When placing the wooden or glass shafts they appear as shaftless cogwheels 

**To Reproduce**
1. Launch Minecraft
2. Join a World
3. Place a custom shaft

**Expected behavior**
A wooden/glass shaft to appear

**Screenshots**
![2023-09-16_01 01 15](https://github.com/iglee42/CreateCasing/assets/102314941/43d19617-b29d-4b2b-b42f-fb9f39f6aaac)

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft Version 1.19.2
 - Forge Version 43.2.23
 - Mod Version 1.4.2
 - [Other Mods](https://pastebin.com/QViGVhmw)

**Comment by Dejojotheawsome** [comment]
Upon further investigation this seems to be a compatibility issue with Extended Cogwheels

**Comment by iglee42** [comment]
It is not my responsibility to resolve this problem, go see the creator of Create Extended Cogwheels ([https://github.com/Rabbitminers/Extended-Cogwheels/issues](https://github.com/Rabbitminers/Extended-Cogwheels/issues))
