### ISSUE TITLE
[Feature] Create v0.5.1e update

### ISSUE THREAD

**Issue by BilalSonmez** [iglee42/CreateCasing#46]
After updating the "Create" mod to version "v0.5.1e". Encased gives an error during login.

I just wanted to let you know

![image](https://github.com/iglee42/CreateCasing/assets/19197491/3689b68d-d499-46d3-a724-cb99077e8003)

MC: 1.20.1
Forge: 47.1.47

**Comment by iglee42** [comment]
Duplicate #42
