### ISSUE TITLE
[Feature] Fabric Support

### ISSUE THREAD

**Issue by adaliszk** [iglee42/CreateCasing#53]
**Is your feature request related to a problem? Please describe.**
I am running a fabric server with many of the create addons already supporting it; my problem is that while I'd like to use this really nice-looking addon, I cannot as it is forge only.

**Describe the solution you'd like**
It would be nice to include a fabric build process as well.

**Describe alternatives you've considered**
I've considered just hiding all the create elements and not trying to encase them. Another alternative I was thinking on to port the textures to a datapack so that it is mod-independent and just retextures things.

**Additional context**
I am running the latest fabric-patched server on Alpine, with Java 17 and Minecraft 1.20.1

**Comment by ebaystudio** [comment]
I second this. Ive seen allot of people asking for it on forums and it would be great if the dev could support other launchers.

**Comment by iglee42** [comment]
I don't know how to dev on fabric so it's no
