### ISSUE TITLE
[Bug] [Forge - 1.19.2]: References to 1.20.x features in loot tables

### ISSUE THREAD

**Issue by SiverDX** [iglee42/CreateCasing#54]
Don't know if they're obtainable but its logging annoying errors
- createcasing:blocks/industrial_iron_encased_cherry_shaft
- createcasing:blocks/copper_glass_encased_shaft
- createcasing:blocks/copper_clear_glass_encased_shaft
- createcasing:blocks/industrial_iron_encased_bamboo_shaft

**Comment by iglee42** [comment]
It's not a big problem I will fix it but it doesn't have an impact on the gameplay

**Comment by iglee42** [comment]
Also for Copper glass encased shaft & copper clear glass encased shaft it's for the compatibility with Create Crystal Clear

**Comment by iglee42** [comment]
Files are removed
