### ISSUE TITLE
[Bug] simple lil bug with train encased pipes

### ISSUE THREAD

**Issue by poly-1810** [iglee42/CreateCasing#55]
**Describe the bug**
train encased pipes dont have connected textures apparently

**To Reproduce**
1. Launch Minecraft
2. Join a World
3. encase a pipe with a train casing, then put train casings around that so the not pipe face is surrounded by train casing

**Expected behavior**
connected textures with regular train casings?

**Screenshots**
![image](https://github.com/iglee42/CreateCasing/assets/105131270/60e8fab2-a7de-4024-8ebc-61d930f8741b)

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft Version: 1.18.2
 - Forge Version: 40.2.9
 - Mod Version: latest on curseforge
 - other mods: https://curseforge.com/minecraft/modpacks/create-charged-up

**Additional context**
the connected textures work just fine with other casings, just not train casings
![image](https://github.com/iglee42/CreateCasing/assets/105131270/052d76a9-03b7-4adc-9fa9-14d40e779ff9)
![image](https://github.com/iglee42/CreateCasing/assets/105131270/e8574ecb-5cdd-4a7f-bfdf-726a71f289a7)
![image](https://github.com/iglee42/CreateCasing/assets/105131270/8da0ace9-b28c-451e-becd-be52d622f4ef)
![image](https://github.com/iglee42/CreateCasing/assets/105131270/8f852634-d26f-47a3-989d-bb83a4dd947c)
(last image is a joke, industrial iron just doesnt have connected textures)

**Comment by iglee42** [comment]
It's no a problem I juste can't make connected textures for that
