### ISSUE TITLE
[Bug] 1.19.2 v1.1 Error Loading Mods

### ISSUE THREAD

**Issue by Shadowscamp** [iglee42/CreateCasing#6]
**Describe the bug**
Looks like there's an error with loading this mod with the latest versions of Create and Flywheel on 1.19.2. The only mods loaded in this instance were Create v0.5.0i, Flywheel v0.6.8.a, and Create Encased v1.1.

**To Reproduce**
1. Launch Minecraft Forge 1.19.2 with Create v0.5.0i, Flywheel v0.6.8.a, and Create Encased v1.1
2. Error Loading Mods

**Expected behavior**
Game load.

**Screenshots**
![image](https://user-images.githubusercontent.com/105675382/224515137-89d7e7e7-7403-41c9-b812-73c969bffbfe.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft Version: 1.19.2
 - Forge Version: 43.2.0
 - Mod Version: 1.1
 - Other Mods: [Create v0.5.0i](https://www.curseforge.com/minecraft/mc-mods/create/files/4371809), [Flywheel v0.6.8.a](https://www.curseforge.com/minecraft/mc-mods/flywheel/files/4341471)

**Additional context**

Crashlog:
https://gist.github.com/Shadowscamp/a0a600888bb71f0f15100785bbcdbac7

**Comment by iglee42** [comment]
Hey I see the problem and I will fix it

**Comment by iglee42** [comment]
Hey , the problem was fix and deploy at the next update
