### ISSUE TITLE
[Bug] Mechanical Arms cannot target custom depots.

### ISSUE THREAD

**Issue by PINPAL** [iglee42/CreateCasing#61]
**Describe the bug**
When attempting to setup a Mechanical arm, you cannot use a custom depot for either taking or placing items.

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch Minecraft
2. Join a World
3. Place down a custom depot.
4. Obtain a Mechanical Arm and attempt to shift click on a depot.
5. Observe no highlight or targeting status is set.
6. Place your Mechanical Arm.
7. Observe the arm has no targets.

**Expected behaviour**
Mechanical Arm is able to target custom depots as if they are the same as base Create.

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft Version: `1.19.2`
 - Forge Version: `40.3.0`
 - Mod Version `1.5.0-ht1`
 - Other Mods: `create-1.19.2-0.5.1.c`

**Comment by iglee42** [comment]
Fixed
