### ISSUE TITLE
[Bug] Industrial Iron Encased Cogwheel and Large Cogwheel break instantly by hand, drop encased block

### ISSUE THREAD

**Issue by stascatto** [iglee42/CreateCasing#62]
**Describe the bug**
These two blocks don't seem to have the proper hardness values and drop as Encased Cogwheels instead of just Cogwheels, very easy to break on accident

**To Reproduce**
1. Place Cogwheel
2. Right click with Industrial Iron
3. Punch Encased Cogwheel

**Expected behavior**
The Industrial Iron Encased Cogwheels take long to break by hand

**Desktop (please complete the following information):**
 - OS: Windows 11 22621
 - Minecraft Version: 1.20.1
 - Forge Version: NeoForge 47.1.81
 - Mod Version: 1.5.0-ht3
 - Other Mods: Create, Embeddium, Oculus, JEI, EMI

**Comment by iglee42** [comment]
That will be fixed
