### ISSUE TITLE
[Bug] Creative casing isnt registered in create encased tab

### ISSUE THREAD

**Issue by DariusZeBaguette** [iglee42/CreateCasing#65]
**Describe the bug**
The Creative casing from create encased is not in create encased's creative tab, nor in any tab so you can research it

**To Reproduce**
1. Launch Minecraft
2. Join a World
3. Open creative inventory
4. research "creative casing" or go to create encased's tab

**Expected behavior**
You see the creative casing in create encased's tab

**Screenshots**
![image](https://github.com/iglee42/CreateCasing/assets/128926506/2a66311c-549f-419c-881b-58dc3c62f1e7)

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft Version : 1.19.2
 - Forge Version 43.3.0
 - Mod Version : 1.6.0
 - A bunch of other create addons

**Comment by iglee42** [comment]
Fixed
