### ISSUE TITLE
[Feature] creative casing should make metal sound

### ISSUE THREAD

**Issue by DariusZeBaguette** [iglee42/CreateCasing#66]
**Is your feature request related to a problem? Please describe.**
It seems like the creative casing makes wood sounds, even if its made out of industrial iron and not wood, and thats odd

**Describe the solution you'd like**
Replace the wood sound by industrial iron sound

**Describe alternatives you've considered**
if you don't like industrial iron sound, you can still use the basic iron block sound

**Comment by iglee42** [comment]
It was a mistake , it's fixed
