### ISSUE TITLE
[Bug]  Tried to get a wrench or open create creative inventory and crashes (extended cogwheels related?)

### ISSUE THREAD

**Issue by DragonGirl7567** [iglee42/CreateCasing#7]
**Describe the bug**
I tried to get a wrench in the creative inventory search and the game crashed. when I tried the creative create inventory, it crashed too. Sorry to bother you.

**To Reproduce**
1. Launch Minecraft
2. Join a World
3. search for a wrench or go to creative inventory to create
4. See the error

**Expected behavior**
crashes and error appears (see below of screenshot

**Screenshots**
![Capture](https://user-images.githubusercontent.com/99091439/225758814-b8df7023-8722-4e7e-b999-3cf04ed2c227.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft Version 1.19.2
 - Forge Version 43.0.0
 - Create: Extended Cogwheels | Rabbitminers | extendedgears-1.19.2-0.5.0g-1.1.2.jar
 - Flywheel | jozufozu | flywheel-forge-1.19.2-0.6.8.a.jar

**Additional context**
Sorry to bother

**Comment by iglee42** [comment]
Can I have a crash report

**Comment by iglee42** [comment]
And can I have create version

**Comment by DragonGirl7567** [comment]
sorry,

create-1.19.2-0.5.0.i.jar

The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: com/cyvack/create_crystal_clear/blocks/glass_encased_cogwheel/GlassEncasedCogwheel


[crash-2023-03-17_10.36.55-client.txt](https://github.com/iglee42/CreateCasing/files/11002466/crash-2023-03-17_10.36.55-client.txt)

Hope this helps, sorry for the inconvenience.

**Comment by iglee42** [comment]
Can you try to update the version of Forge ?

**Comment by iglee42** [comment]
That Was fix in new update

**Comment by DragonGirl7567** [comment]
sorry to bother

**Comment by DragonGirl7567** [comment]
I am sorry but still experiencing an error with the Extended Gears mod.

Error: java.lang.NullPointerException: Registry entry not present: createcasing-extendedgears:brass_dark_oak_encased_cogwheel

sorry, the error above (in previous comments) involved the crystal clear mod. I even used the most recent forge version: Forge - 43.2.7

 I am so sorry if I am being a nuisance.
[crash-2023-03-17_18.35.38-client.txt](https://github.com/iglee42/CreateCasing/files/11006823/crash-2023-03-17_18.35.38-client.txt)

**Comment by iglee42** [comment]
Hey, it doesn't matter to make reports, on the contrary it helps the mod to improve

**Comment by iglee42** [comment]
And I know this crash but I don't know where it comes from

**Comment by iglee42** [comment]
That Fix
