### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by pospech03** [iglee42/CreateCasing#71]
Can't use train mixer on AE2 fluix crystal recipy. It infinitly spins but dont make any crystals

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft Version 1.20.1
 - Forge Version 47.2.0
 - Mod Version: 1.20.1-1.6.0
 - Other Mods

**Additional context**
If I use any other mixer that dont have the 2x speed it works

**Comment by iglee42** [comment]
Duplicate from #68
