### ISSUE TITLE
Add zh_cn for Create Encased [Feature]

### ISSUE THREAD

**Issue by Y-Xiao233** [iglee42/CreateCasing#73]
Hello,iglee42,I really like this mod, just like most Chinese people, but it doesn't have Chinese. So I translated some important content and put it in the whole paragraph below, hoping to add it to the mod. Thank you very much!

{
    "block.createcasing.creative_casing":"创造机壳",
    "block.createcasing.vertical_brass_gearbox":"黄铜竖直十字齿轮箱",
    "block.createcasing.vertical_copper_gearbox":"铜竖直十字齿轮箱",
    "block.createcasing.vertical_railway_gearbox":"列车竖直十字齿轮箱",
    "block.createcasing.vertical_creative_gearbox":"创造竖直十字齿轮箱",
    "block.createcasing.vertical_industrial_iron_gearbox":"工业铁竖直十字齿轮箱",
    "block.createcasing.brass_gearbox":"黄铜十字齿轮箱",
    "block.createcasing.copper_gearbox":"铜十字齿轮箱",
    "block.createcasing.railway_gearbox":"列车十字齿轮箱",
    "block.createcasing.creative_gearbox":"创造十字齿轮箱",
    "block.createcasing.brass_mixer":"黄铜动力搅拌器",
    "block.createcasing.copper_mixer":"铜动力搅拌器",
    "block.createcasing.railway_mixer":"列车动力搅拌器",
    "block.createcasing.creative_mixer":"创造动力搅拌器",
    "block.createcasing.industrial_iron_mixer":"工业铁动力搅拌器",
    "block.createcasing.brass_press":"黄铜辊压机",
    "block.createcasing.copper_press":"铜辊压机",
    "block.createcasing.railway_press":"列车辊压机",
    "block.createcasing.creative_press":"创造辊压机",
    "block.createcasing.industrial_iron_press":"工业铁辊压机",
    "block.createcasing.brass_depot":"黄铜置物台",
    "block.createcasing.copper_depot":"铜置物台",
    "block.createcasing.railway_depot":"列车置物台",
    "block.createcasing.creative_depot":"创造置物台",
    "block.createcasing.industrial_iron_depot":"工业铁置物台",
    "block.createcasing.brass_encased_chain_drive":"黄铜链式传动箱",
    "block.createcasing.copper_encased_chain_drive":"铜链式传动箱",
    "block.createcasing.railway_encased_chain_drive":"列车链式传动箱",
    "block.createcasing.creative_encased_chain_drive":"创造链式传动箱",
    "block.createcasing.industrial_iron_encased_chain_drive":"工业铁链式传动箱",
    "block.createcasing.brass_adjustable_chain_gearshift":"黄铜可调节链式传动箱",
    "block.createcasing.copper_adjustable_chain_gearshift":"铜可调节链式传动箱",
    "block.createcasing.railway_adjustable_chain_gearshift":"列车可调节链式传动箱",
    "block.createcasing.creative_adjustable_chain_gearshift":"创造可调节链式传动箱",
    "block.createcasing.industrial_iron_adjustable_chain_gearshift":"工业铁可调节链式传动箱",
    "block.createcasing.creative_cogwheel":"创造齿轮箱",
    "block.createcasing.copper_glass_encased_shaft":"铜玻璃传动杆箱",
    "block.createcasing.copper_clear_glass_encased_shaft":"铜通透玻璃传动杆箱",
    "block.createcasing.copper_glass_encased_cogwheel":"铜玻璃齿轮箱",
    "block.createcasing.copper_clear_glass_encased_cogwheel":"铜通透玻璃齿轮箱",
    "block.createcasing.copper_glass_encased_large_cogwheel":"铜玻璃大齿轮箱",
    "block.createcasing.copper_clear_glass_encased_large_cogwheel":"铜通透玻璃大齿轮箱",
    "block.createcasing.oak_shaft":"橡木传动杆",
    "block.createcasing.spruce_shaft":"云杉木传动杆",
    "block.createcasing.birch_shaft":"白桦木传动杆",
    "block.createcasing.jungle_shaft":"从林木传动杆",
    "block.createcasing.acacia_shaft":"金合欢传动杆",
    "block.createcasing.dark_oak_shaft":"深色橡木传动杆",
    "block.createcasing.mangrove_shaft":"红树木传动杆",
    "block.createcasing.crimson_shaft":"绯红菌柄传动杆",
    "block.createcasing.warped_shaft":"诡异菌柄传动杆",
    "block.createcasing.glass_shaft":"玻璃传动杆",
    "block.createcasing.brass_shaft":"黄铜传动杆"
}
<img width="859" alt="{15285B31-965E-4215-B209-BE215B7D72F2}" src="https://github.com/iglee42/CreateCasing/assets/159413429/376aa916-8659-401f-9795-86a6b0c727d9">

**Comment by iglee42** [comment]
Can you make a pull request please

**Comment by iglee42** [comment]
And Chinese is normally in the mod
