### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by CrimsonExe** [iglee42/CreateCasing#74]
**Describe the bug**
Encased Blocks seemed to be a different shade of color compared to other andesite casings

**To Reproduce**
I am playing on the Steampunk LPS modpack This occurred after the patch update happens with shaders on or off. 

**Expected behavior**

**Screenshots**
shaders on
![image](https://github.com/iglee42/CreateCasing/assets/147616507/64df828d-5034-4d1e-989f-e3205e01c146)

Shaders off
![image](https://github.com/iglee42/CreateCasing/assets/147616507/c8333017-1994-429f-a9e0-c3ca11431620)

**Desktop (please complete the following information):**
 - OS: [windows 11]
 - Minecraft Version [1.19.2]
 - Forge Version [43.3.5]
 - Mod Version [not sure how to check]
 - Other Mods

**Additional context**

**Comment by iglee42** [comment]
If this is with andesite & brass cogwheels it's a bug from Create and not my mod
