### ISSUE TITLE
JEI not showing only Industrial Iron Gearxc

### ISSUE THREAD

**Issue by CyaniideDrive** [iglee42/CreateCasing#76]
**Describe the bug**
Normal Industrial Iron Gearboxes don't exist in JEI but Vertical ones do.

**To Reproduce**
Try to search for Industrial Iron Gearbox in JEI.
Only Vertical Gearbox.

**Expected behavior**
The horizontal gearbox should be in JEI just like the vertical one is.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Minecraft Version 1.18.2
 - Forge Version 40.2.8
 - Mod Version 1.18.2-1.6.0-ht1
 - Other Mods: I'm using the mod on CABIN, a forward port of Create: Above and Beyond, but I'm not entirely sure if that would mess with what JEI shows to cause this since the other gearboxes show up just fine.

**Additional context**
I haven't tried the 1.20.1 version of this update, but I'm guessing JEI works fine there and that's why it hasn't been reported yet.
![image](https://github.com/iglee42/CreateCasing/assets/2701541/e7ab951d-633f-4406-a4a4-f1661529c0d7)

**Comment by iglee42** [comment]
I think it's just an oversight on my part, is it in the creative tab?
