### ISSUE TITLE
all shafts are using the wrong model [Bug] 

### ISSUE THREAD

**Issue by ghost** [iglee42/CreateCasing#77]
**Describe the bug**
when placing a oakshaft for example it shows a cog without a shaft

**To Reproduce**
1. Launch Minecraft
2. Join a World
3. Right Click on '...'

**Expected behavior**
a shaft

**Screenshots**
![2024-05-08_12 19 50](https://github.com/iglee42/CreateCasing/assets/149600452/b3f03fe2-2c3d-4d8d-9f11-bfb869f009cd)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Minecraft Version [1.20.1]
 - Forge Version [47.2.17]
 - Mod Version [1.6.0]
 - most create addons

**Additional context**
no additional

**Comment by iglee42** [comment]
![Screenshot_2024-05-08-12-23-39-959_com.discord.jpg](https://github.com/iglee42/CreateCasing/assets/50081542/57eaac45-5e3c-43e5-8357-7c1f30c386cb)
