### ISSUE TITLE
[Bug] Creative Casing connected textures

### ISSUE THREAD

**Issue by Lucky-56** [iglee42/CreateCasing#78]
**Describe the bug**
The `Creative Casing` doesn't connect correctly

**To Reproduce**
1. Launch Minecraft
2. Join a World
3. place `Creative Casing` in a plus shape
4. observe

**Expected behavior**
The edges of the texture connecting. *see brass plus in screenshot*

**Screenshots**
![2024-05-26_14 04 47](https://github.com/iglee42/CreateCasing/assets/55949451/4cfdee58-3aca-4754-a531-339e2f80667c)

**Desktop:**
 - OS: Windows 11
 - Minecraft Version 1.20.1
 - Forge Version 47.2.32
 - Mod Version 1.6.0
 - Other Mods:
   - too long of a modlist (not applicable)

**Comment by iglee42** [comment]
Hello, this is not a bug, it is due to the creative casing sprite sheet and therefore it is totally normal

**Comment by Lucky-56** [comment]
oh :(
not even fixable with resource pack tho?

**Comment by iglee42** [comment]
Technically this could be fixed if someone made the connected texture file like the brass one
