### ISSUE TITLE
[Bug] Brass Mixer will not process items

### ISSUE THREAD

**Issue by Lainwright-Lazuli** [iglee42/CreateCasing#79]
**Describe the bug**
Brass Mixer won't mix items, but the normal mixer will.
The mixer will accept any valid recipe (moving the whisk down), but it will not mix.

**To Reproduce**
1. Create a new world
2. Power a Mechanical Mixer
3. Test to make sure that the Mechanical Mixer works (use Andesite Alloy as a test)
4. Replace Mechanical Mixer with Brass Mixer
5. Try and fail to have it mix something like Andesite Alloy

**Expected behavior**
The Brass Mixer should at least be able to mix items.

**Screenshots**
![bep1](https://github.com/iglee42/CreateCasing/assets/47049538/669eb765-9321-4aea-8f91-c40a5bf4e50b)
![bep2](https://github.com/iglee42/CreateCasing/assets/47049538/ae0ab23f-3c5a-46e4-a2b3-6a4e319ac0cd)
![bep3](https://github.com/iglee42/CreateCasing/assets/47049538/bf1a5977-0438-4351-b398-4e672c02211c)
![bep4](https://github.com/iglee42/CreateCasing/assets/47049538/f29130fa-ef7e-42c4-ba95-b0f4f7005399)
![bep5](https://github.com/iglee42/CreateCasing/assets/47049538/16a1e2cb-e82e-4138-a328-81042fbb9174)

The first three images show that the mixer has a proper setup and does not lack RPM or have other issues.
The last 2 images show that the regular mixer works, even with modded recipes.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft Version 1.20.1
 - Forge Version 47.2.0
 - Mod Version 1.20.1-1.6.0-fix1.jar
 - Other Mods

**Additional context**
![a4](https://github.com/iglee42/CreateCasing/assets/47049538/46c2b696-e3f1-4ae8-b89a-6318014302e4)
![a3](https://github.com/iglee42/CreateCasing/assets/47049538/4dbfa5a7-2ffa-4e4b-a90c-cce188cca630)
![a2](https://github.com/iglee42/CreateCasing/assets/47049538/3bf3ea47-c1bb-4b4e-a054-3625a6c81856)
![a1](https://github.com/iglee42/CreateCasing/assets/47049538/7917b617-7b35-4025-aced-03a3727d45e4)

Just had this troubleshooted in Create Discord. I can thankfully mix items, but not with the Brass Mixer from Create: Encased.
I had the regular mixer finish mixing in a few seconds (around ~5 or so for Andesite Alloy) but fail to mix it in a few minutes with a Brass Mixer.

**Comment by iglee42** [comment]
Does it with other mixers ?

**Comment by iglee42** [comment]
Duplicate from #68

**Comment by Lainwright-Lazuli** [comment]
Train Mixer and Copper Mixer do not work.

**Comment by iglee42** [comment]
I think that can be fixed by disabling the option that mixe x2 in the config

**Comment by iglee42** [comment]
@Lainwright-Lazuli I want to know if I give you an experimental build, if you can test if the fix work ?

**Comment by iglee42** [comment]
Fixed In the next update
