### ISSUE TITLE
[Bug] This mod with Universal Sawmill causes "Invalid Player Data" issue

### ISSUE THREAD

**Issue by AndreAugustoDev** [iglee42/CreateCasing#80]
**Describe the bug**
This mod with Universal Sawmill causes "Invalid Player Data" issue

**To Reproduce**
1. Launch Minecraft
2. Try join server
3. See error

**Expected behavior**
Join server without issue

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version 1.20.1
 - NeoForge Version 47.1.106
 - Mod Version 1.6.1
 - Universal Sawmill in custom modpack

**Additional context**
[latest.log](https://github.com/user-attachments/files/15892778/latest.log)
https://github.com/MehVahdJukaar/sawmill/issues/39
https://github.com/gigaherz/Guidebook/issues/118
https://github.com/gigaherz/Guidebook/commit/aa00edc3e8012c68c938a5eefadb1adf73c4a395

**Probably fix**
Add `if (EffectiveSide.get().isServer()) return;` at fr.iglee42.createcasing.registries.ModCreativeModeTabs#L50  https://github.com/iglee42/CreateCasing/blob/1071adc29140bf3c20559681439881fd5ea347d9/src/main/java/fr/iglee42/createcasing/registries/ModCreativeModeTabs.java#L50

**Comment by iglee42** [comment]
Line 50 is empty are you sure that is the correct line

**Comment by AndreAugustoDev** [comment]
Yes, it is correct.
There add the check similar to what was done in the mentioned issues.

**Comment by AndreAugustoDev** [comment]
[latest.log from server](https://mclo.gs/PnOKkTj)
See https://mclo.gs/PnOKkTj#L5387

**Comment by iglee42** [comment]
The fix was commit but Curseforge is bugged so the update can't be pushed officially
