### ISSUE TITLE
[Bug] Messes with Create assisted placement

### ISSUE THREAD

**Issue by bsylve1996** [iglee42/CreateCasing#84]
**Describe the bug**
If you try to place a cog, the assisted placement is not in the correct position. It shows in the spot of a shaft instead of where a cog should be. Sometimes will place in the correct position even though the assisted vision is wrong. But most of time will place incorrectly matching the incorrect assisted placement. 

You have to place a block on both sides of a cog to place cogs correctly most of the time.

version: 1.20.1-1.6.1

**Comment by iglee42** [comment]
Fixed in the next update
