### ISSUE TITLE
[Bug] Encased chain drives from this mod don’t drive each other when placed directly adjacent, as base Create ones do

### ISSUE THREAD

**Issue by mbwarn** [iglee42/CreateCasing#86]
**Describe the bug**
When placing an encased chain drive (for example, copper) directly in front of another one that is already turning (so that the shaft sides are touching), the second drive does not turn. This is not the same as the behavior of the base Create chain drives with andesite casings. You can workaround this by inserting a shaft in between, but this costs another block worth of space.

**To Reproduce**
1. Place a series of at least two copper (etc) encased chain drives side-by-side connected with a rotation source, so that the drives are turning and there is an exposed shaft-side of at least one chain drive
2. Place another copper (etc) encased chain drive against the first series, such that the “shaft sides” are touching.
3. Observe the bug. The original drive series keeps turning, but the new drive does not turn

**Expected behavior**
Chain drives in different series should be able to drive each other when connected shaft-to-shaft

**Desktop (please complete the following information):**
 - OS: macOS, but this is on a server so it’s not relevant
 - Minecraft Version 1.20.1
 - Forge Version 47.3.0
 - Mod Version 1.6.1
 - Other Mods: over 200, mostly other Create add-ons, and Pneumaticraft. It would be prohibitive to list them all here. I guess if this chain drive behavior is expected even though it contradicts base Create, it’s a bug, and if it doesn’t, it’s not. This should be trivial to test. 

**Additional context**
Love the mod, thanks for your work. Sorry if this bug report isn’t rigorous enough, banging it out between other work of my own.

**Comment by iglee42** [comment]
Did you try with the last fix ?

**Comment by mbwarn** [comment]
> Did you try with the last fix ?

It looks like it's fixed in 1.6.1_fixed

Sorry, it wasn't in the change log so I figured it wasn't addressed. Behavior is as expected now. Thanks!

**Comment by iglee42** [comment]
Normally it was fix in 1.6.1 but if it works with 1.6.1-fix1 it's OK

**Comment by mbwarn** [comment]
> Normally it was fix in 1.6.1 but if it works with 1.6.1-fix1 it's OK

You are right, we were on 1.60_fix and I had misread it. This issue IS, of course, in the change log.

My apologies. Thanks again!
