### ISSUE TITLE
[Bug] Wooden shafts are rendering as shaftless cogs instead.

### ISSUE THREAD

**Issue by mbwarn** [iglee42/CreateCasing#87]
**Describe the bug**
All of the wooden shafts that are crafted from two stripped logs are being portrayed as shafts in inventory, but rendering as wooden cogs with no shafts when placed. They behave as shafts but show the wrong model. 

**To Reproduce**
1. Craft a wooden shaft
2. Place the shaft, a cog model is displayed instead

**Expected behavior**
Shafts should look like shafts :) 

**Desktop (please complete the following information):**
 - OS: macOS
 - Minecraft Version 1.20.1
 - Forge Version 43.1.7
 - Mod Version 1.6.1 fix 1
 - Other Mods: lots of other Create Add-ons, but nothing niche

**Comment by iglee42** [comment]
As I have said many time : the bug where custom shafts turn into cogwheels is due to the Create: Extended Coghweels mod.
