### ISSUE TITLE
[Bug] Create: Encased is incompatible with the latest version of Create.

### ISSUE THREAD

**Issue by TheDogOfChaos** [iglee42/CreateCasing#89]
**Describe the bug**
Create; Encased is currently incompatible with the latest version of Create, due to something with the mixins related to the mod expecting stuff that is no longer available (i think)

**To Reproduce**
1: Install both Create: Encased 1.20.1-1.6.1-fix2 and Create 1.20.1-0.5.1.h
2: Launch the game.
3: The game will crash while injecting mixins, and take any & every other Create addon with it.

**Expected behavior**
I expected the game to load to the main menu.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft Version: 1.20.1
 - Forge Version: 47.3.7
 - Mod Version: 1.6.1-fix2
 - Other Mods:
   - Create: 0.5.1.h

**Logs:**
[Console Log](https://mclo.gs/aRNouWk)
[Debug Log](https://mclo.gs/ZmuRVkF)
[Crash Log](https://mclo.gs/h8vPHno)

**Comment by iglee42** [comment]
Fixed on curseforge thanks for your report
