### ISSUE TITLE
[Bug] Depots have no right click interaction

### ISSUE THREAD

**Issue by Nerf-Craft** [iglee42/CreateCasing#92]
**Describe the bug**
The four depot variants added by the mod cannot have items placed on or removed from them by right-clicking.

**To Reproduce**
1. Launch Minecraft
2. Join a World
3. Craft a copper, brass, train, or industrial iron depot, and place it.
4. Right Click on the the top face of the depot while holding any item
5. See Error

**Expected behavior**
Item should be placed onto the depot from main hand.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.20.1
 - Forge Version 47.3.0
 - Mod Version 1.6.2

**Additional context**
Items can still be placed on the depot by using the 'drop' button and throwing the item directly onto the depot. The item cannot be removed manually without breaking the depot.

**Comment by iglee42** [comment]
What create version

**Comment by Nerf-Craft** [comment]
The Create version is 0.5.1.i

**Comment by Elrol** [comment]
I am using the 0.5.1.j version and I am also having this issue

**Comment by iglee42** [comment]
I think it's a bug due to 5.1i but I'm in vacations so I can't fix it now

**Comment by BoxWithoutATop** [comment]
Just wanted to say I also have this issue with 5.1j.
