### ISSUE TITLE
Regarding the name of Creative_casing

### ISSUE THREAD

**Issue by ghost** [iglee42/CreateCasing#97]
Perhaps 'Creative Casing' could be changed to 'Chorium Casing' because the raw material for Creative Casing is Chorium Ingot, and 'Creative' generally refers to items that can only be obtained in Creative mode

**Comment by iglee42** [comment]
I won't do it, because the chorium was thought of after the creative casing, it's just a way to obtain it since the creative casing is only used for decoration
